/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import guis.LoginForm;
import java.awt.event.WindowEvent;

import java.util.List;
import java.util.ArrayList;

import users.Admin;
import users.Doctor;
import users.Patient;
import users.Person;
import users.Secretary;

import main.GUISimulator;

/**
 *
 * @author Reece
 */
public class AdminMainForm extends javax.swing.JFrame {
    
    Admin userAdmin;

    /**
     * Creates new form AdminMainForm
     */
    public AdminMainForm() {
        initComponents();
    }
    
    public AdminMainForm(Admin thisAdmin) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.userAdmin = thisAdmin;
        
        idLabel.setText(thisAdmin.getId());
        nameLabel.setText(thisAdmin.getName());
        
        //System.out.println(userAdmin.getId() + " " + userAdmin.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createAdminAccountButton = new javax.swing.JButton();
        manageDoctorAccountsButton = new javax.swing.JButton();
        manageSecretaryAccountButton = new javax.swing.JButton();
        viewDoctorRatingsButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        createDoctorAccountButton = new javax.swing.JButton();
        createSecretaryAccountButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText("Admin");

        createAdminAccountButton.setText("Create Admin Account");
        createAdminAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdminAccountButtonActionPerformed(evt);
            }
        });

        manageDoctorAccountsButton.setText("Manage Doctor Accounts");
        manageDoctorAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorAccountsButtonActionPerformed(evt);
            }
        });

        manageSecretaryAccountButton.setText("Manage Secretary Accounts");
        manageSecretaryAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSecretaryAccountButtonActionPerformed(evt);
            }
        });

        viewDoctorRatingsButton.setText("View Doctor Ratings");
        viewDoctorRatingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorRatingsButtonActionPerformed(evt);
            }
        });

        idLabel.setText("A0000");

        createDoctorAccountButton.setText("Create Doctor Account");
        createDoctorAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDoctorAccountButtonActionPerformed(evt);
            }
        });

        createSecretaryAccountButton.setText("Create Secretary Account");
        createSecretaryAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSecretaryAccountButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(nameLabel))
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createSecretaryAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createAdminAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createDoctorAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageSecretaryAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(manageDoctorAccountsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(viewDoctorRatingsButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOutButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel)))))
                .addGap(25, 25, 25)
                .addComponent(createAdminAccountButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createDoctorAccountButton)
                    .addComponent(manageDoctorAccountsButton)
                    .addComponent(viewDoctorRatingsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSecretaryAccountButton)
                    .addComponent(manageSecretaryAccountButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAdminAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdminAccountButtonActionPerformed
        CreateAdminAccountForm CreateAdminInfo = new CreateAdminAccountForm(this.userAdmin);
        CreateAdminInfo.setVisible(true);
    }//GEN-LAST:event_createAdminAccountButtonActionPerformed

    private void manageDoctorAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorAccountsButtonActionPerformed
        // TODO add your handling code here:
        ManageDoctorAccountsForm ManageDoctorInfo = new ManageDoctorAccountsForm(this.userAdmin);
        ManageDoctorInfo.setVisible(true);
    }//GEN-LAST:event_manageDoctorAccountsButtonActionPerformed

    private void createDoctorAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDoctorAccountButtonActionPerformed
        // TODO add your handling code here:
        CreateDoctorAccountForm CreateDoctorInfo = new CreateDoctorAccountForm(this.userAdmin);
        CreateDoctorInfo.setVisible(true);
    }//GEN-LAST:event_createDoctorAccountButtonActionPerformed

    private void createSecretaryAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSecretaryAccountButtonActionPerformed
        // TODO add your handling code here:
        CreateSecretaryAccountForm CreateSecretaryInfo = new CreateSecretaryAccountForm(this.userAdmin);
        CreateSecretaryInfo.setVisible(true);
    }//GEN-LAST:event_createSecretaryAccountButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm LoginInfo = new LoginForm();
        LoginInfo.setVisible(true);
        
        this.setDefaultCloseOperation(RequestPatientAccountForm.DISPOSE_ON_CLOSE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void manageSecretaryAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSecretaryAccountButtonActionPerformed
        // TODO add your handling code here:
        ManageSecretaryAccountsForm ManageSecretaryInfo = new ManageSecretaryAccountsForm(this.userAdmin);
        ManageSecretaryInfo.setVisible(true);
    }//GEN-LAST:event_manageSecretaryAccountButtonActionPerformed

    private void viewDoctorRatingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorRatingsButtonActionPerformed
        // TODO add your handling code here:
        ViewDoctorRatingsForm ViewDoctorRatingsInfo = new ViewDoctorRatingsForm(this.userAdmin);
        ViewDoctorRatingsInfo.setVisible(true);
    }//GEN-LAST:event_viewDoctorRatingsButtonActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAdminAccountButton;
    private javax.swing.JButton createDoctorAccountButton;
    private javax.swing.JButton createSecretaryAccountButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton manageDoctorAccountsButton;
    private javax.swing.JButton manageSecretaryAccountButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton viewDoctorRatingsButton;
    // End of variables declaration//GEN-END:variables
}
