/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import controller.LoginStrategyController;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import users.Doctor;
import users.Patient;
import users.Secretary;

/**
 *
 * @author Reece
 */
public class CreateAppointmentForm extends javax.swing.JFrame {
    
    Secretary userSecretary;

    /**
     * Creates new form CreateAppointmentForm
     */
    public CreateAppointmentForm() {
        initComponents();
    }
    
    public CreateAppointmentForm(Secretary thisSecretary) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.userSecretary = thisSecretary;
        
        DefaultListModel requestMod = new DefaultListModel();
        requestList.setModel(requestMod);
        
        for (int i = 0; i < this.userSecretary.patientAppointmentRequestList.size(); i++)
        {
            requestMod.addElement(this.userSecretary.patientAppointmentRequestList.get(i).getId());
        }
        
        
        DefaultListModel propositionMod = new DefaultListModel();
        propositionList.setModel(propositionMod);
        
        for (int i = 0; i < this.userSecretary.doctorAppointmentRequestList.size(); i++)
        {
            propositionMod.addElement(this.userSecretary.doctorAppointmentRequestList.get(i).getId());
        }
        
        DefaultComboBoxModel comboDMod = new DefaultComboBoxModel();
        doctorComboBox.setModel(comboDMod);
        
        for (int i = 0; i < LoginStrategyController.doctorList.size(); i++) {
            
            comboDMod.addElement(LoginStrategyController.doctorList.get(i).getId());
        }
        
        DefaultComboBoxModel comboPMod = new DefaultComboBoxModel();
        patientComboBox.setModel(comboPMod);
        
        for (int i = 0; i < LoginStrategyController.patientList.size(); i++) {
            
            comboPMod.addElement(LoginStrategyController.patientList.get(i).getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pIdLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        viewPDetailsButton = new javax.swing.JButton();
        pNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pAgeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestList = new javax.swing.JList<>();
        pAddressLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dAgeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        propositionList = new javax.swing.JList<>();
        dIdLabel = new javax.swing.JLabel();
        dAddressLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewDDetailsButton = new javax.swing.JButton();
        dNameLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pDateLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pDNameLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dDateLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dPNameLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        createAppointmentButton = new javax.swing.JButton();
        doctorComboBox = new javax.swing.JComboBox<>();
        patientComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create an Appointment");

        pIdLabel.setText("*ID*");

        jLabel2.setText("Name:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        viewPDetailsButton.setText("View Patient Details");
        viewPDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPDetailsButtonActionPerformed(evt);
            }
        });

        pNameLabel.setText("*NAME*");

        jLabel4.setText("Age:");

        jLabel5.setText("Address:");

        pAgeLabel.setText("*AGE*");

        requestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(requestList);

        pAddressLabel.setText("*ADDRESS*");

        jLabel6.setText("Pending patient requests");

        jLabel7.setText("Address:");

        dAgeLabel.setText("*AGE*");

        propositionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(propositionList);

        dIdLabel.setText("*ID*");

        dAddressLabel.setText("*ADDRESS*");

        jLabel8.setText("Name:");

        jLabel9.setText("Pending doctor propositions");

        jLabel10.setText("ID:");

        viewDDetailsButton.setText("View Doctor Details");
        viewDDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDDetailsButtonActionPerformed(evt);
            }
        });

        dNameLabel.setText("*NAME*");

        jLabel11.setText("Age:");

        jLabel12.setText("Date requested:");

        pDateLabel.setText("*DATE*");

        jLabel14.setText("Doctor requested");

        pDNameLabel.setText("*DOCTOR NAME*");

        jLabel16.setText("Date requested:");

        dDateLabel.setText("*DATE*");

        jLabel18.setText("Patient requested");

        dPNameLabel.setText("*PATIENT NAME*");

        jLabel13.setText("Create a Specific Appointment");

        jLabel15.setText("Date of appointment (DD/MM/YYYY)");

        jLabel17.setText("With doctor (ID)");

        jLabel19.setText("with patient (ID)");

        createAppointmentButton.setText("Create Appointment");
        createAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAppointmentButtonActionPerformed(evt);
            }
        });

        doctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewPDetailsButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pAgeLabel)
                                            .addComponent(pIdLabel)
                                            .addComponent(pNameLabel)
                                            .addComponent(pAddressLabel)
                                            .addComponent(pDateLabel)
                                            .addComponent(pDNameLabel)))))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dAgeLabel)
                                            .addComponent(dIdLabel)
                                            .addComponent(dNameLabel)
                                            .addComponent(dAddressLabel)))
                                    .addComponent(viewDDetailsButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dDateLabel)
                                            .addComponent(dPNameLabel))))))
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(createAppointmentButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateTextField)
                                    .addComponent(doctorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel13)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewPDetailsButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(pNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(pIdLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(pAgeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(pAddressLabel))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(pDateLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(pDNameLabel)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewDDetailsButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(dNameLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(dIdLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(dAgeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(dAddressLabel))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(dDateLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(dPNameLabel)))
                            .addComponent(jScrollPane2))))
                .addGap(54, 54, 54)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createAppointmentButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(RequestPatientAccountForm.DISPOSE_ON_CLOSE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void viewPDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPDetailsButtonActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < this.userSecretary.patientAppointmentRequestList.size(); i++)
        {
            if (this.userSecretary.patientAppointmentRequestList.get(i).getId() == requestList.getSelectedValue())
            {
                pNameLabel.setText(this.userSecretary.patientAppointmentRequestList.get(i).getName());
                pIdLabel.setText(this.userSecretary.patientAppointmentRequestList.get(i).getId());
                pAgeLabel.setText(Integer.toString(this.userSecretary.patientAppointmentRequestList.get(i).getAge()));
                pAddressLabel.setText(this.userSecretary.patientAppointmentRequestList.get(i).getAddress());
            }
        }
    }//GEN-LAST:event_viewPDetailsButtonActionPerformed

    private void viewDDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDDetailsButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < this.userSecretary.doctorAppointmentRequestList.size(); i++)
        {
            if (this.userSecretary.doctorAppointmentRequestList.get(i).getId() == propositionList.getSelectedValue())
            {
                dNameLabel.setText(this.userSecretary.doctorAppointmentRequestList.get(i).getName());
                dIdLabel.setText(this.userSecretary.doctorAppointmentRequestList.get(i).getId());
                dAgeLabel.setText(Integer.toString(this.userSecretary.doctorAppointmentRequestList.get(i).getAge()));
                dAddressLabel.setText(this.userSecretary.doctorAppointmentRequestList.get(i).getAddress());
            }
        }
    }//GEN-LAST:event_viewDDetailsButtonActionPerformed

    private void createAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAppointmentButtonActionPerformed
        // TODO add your handling code here:
        Doctor doctorSelected = null;
        Patient patientSelected = null;
        
        String doctorId = doctorComboBox.getSelectedItem().toString();
        String patientId = patientComboBox.getSelectedItem().toString();
        
        for (int i = 0; i < LoginStrategyController.doctorList.size(); i++)
        {
            System.out.println("Looking: " + LoginStrategyController.doctorList.get(i).getId() + " != " + doctorId);
            
            if (LoginStrategyController.doctorList.get(i).getId() == doctorId)
            {
                System.out.println("Doctor reference found");
                doctorSelected = LoginStrategyController.doctorList.get(i);
            }
        }
        
        for (int i = 0; i < LoginStrategyController.patientList.size(); i++)
        {
            System.out.println("Looking: " + LoginStrategyController.patientList.get(i).getId() + " != " + patientId);
            if (LoginStrategyController.patientList.get(i).getId() == patientId)
            {
                System.out.println("Patient reference found");
                patientSelected = LoginStrategyController.patientList.get(i);
            }
        }
        
        this.userSecretary.createAppointment(doctorSelected, patientSelected, dateTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Appointment created", "Alert", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_createAppointmentButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createAppointmentButton;
    private javax.swing.JLabel dAddressLabel;
    private javax.swing.JLabel dAgeLabel;
    private javax.swing.JLabel dDateLabel;
    private javax.swing.JLabel dIdLabel;
    private javax.swing.JLabel dNameLabel;
    private javax.swing.JLabel dPNameLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JComboBox<String> doctorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pAddressLabel;
    private javax.swing.JLabel pAgeLabel;
    private javax.swing.JLabel pDNameLabel;
    private javax.swing.JLabel pDateLabel;
    private javax.swing.JLabel pIdLabel;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JComboBox<String> patientComboBox;
    private javax.swing.JList<String> propositionList;
    private javax.swing.JList<String> requestList;
    private javax.swing.JButton viewDDetailsButton;
    private javax.swing.JButton viewPDetailsButton;
    // End of variables declaration//GEN-END:variables
}
