/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.awt.event.WindowEvent;
import users.Doctor;


/**
 *
 * @author Reece
 */
public class DoctorMainForm extends javax.swing.JFrame {
    
    Doctor userDoctor;
    

    /**
     * Creates new form DoctorMainForm
     */
    public DoctorMainForm() {
        initComponents();
    }
    
    public DoctorMainForm(Doctor thisDoctor) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.userDoctor = thisDoctor;
        
        idLabel.setText(thisDoctor.getId());
        nameLabel.setText(thisDoctor.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        appointmentsButton = new javax.swing.JButton();
        patientsButton = new javax.swing.JButton();
        medicinesButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        myFeedbackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Doctor");

        appointmentsButton.setText("Appointments");
        appointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentsButtonActionPerformed(evt);
            }
        });

        patientsButton.setText("Patients");
        patientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsButtonActionPerformed(evt);
            }
        });

        medicinesButton.setText("Medicines");
        medicinesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinesButtonActionPerformed(evt);
            }
        });

        idLabel.setText("D0000");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        myFeedbackButton.setText("My Feedback");
        myFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myFeedbackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myFeedbackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appointmentsButton)
                                .addGap(18, 18, 18)
                                .addComponent(patientsButton)
                                .addGap(18, 18, 18)
                                .addComponent(medicinesButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(logOutButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentsButton)
                    .addComponent(patientsButton)
                    .addComponent(medicinesButton))
                .addGap(18, 18, 18)
                .addComponent(myFeedbackButton)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm LoginInfo = new LoginForm();
        LoginInfo.setVisible(true);

        this.setDefaultCloseOperation(RequestPatientAccountForm.DISPOSE_ON_CLOSE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void appointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentsButtonActionPerformed
        // TODO add your handling code here:
        DoctorAppointmentsForm doctorAppInfo = new DoctorAppointmentsForm(this.userDoctor);
        doctorAppInfo.setVisible(true);
    }//GEN-LAST:event_appointmentsButtonActionPerformed

    private void patientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsButtonActionPerformed
        // TODO add your handling code here:
        PatientsForm patientInfo = new PatientsForm(this.userDoctor);
        patientInfo.setVisible(true);
    }//GEN-LAST:event_patientsButtonActionPerformed

    private void medicinesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinesButtonActionPerformed
        // TODO add your handling code here:
        MedicineForm medicineInfo = new MedicineForm(this.userDoctor);
        medicineInfo.setVisible(true);
    }//GEN-LAST:event_medicinesButtonActionPerformed

    private void myFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFeedbackButtonActionPerformed
        // TODO add your handling code here:
        ViewFeedbackForm viewFeedInfo = new ViewFeedbackForm(this.userDoctor);
        viewFeedInfo.setVisible(true);
    }//GEN-LAST:event_myFeedbackButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentsButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton medicinesButton;
    private javax.swing.JButton myFeedbackButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton patientsButton;
    // End of variables declaration//GEN-END:variables
}
