/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.awt.event.WindowEvent;
import users.Secretary;

/**
 *
 * @author Reece
 */
public class SecretaryMainForm extends javax.swing.JFrame {
    
    Secretary userSecretary;

    /**
     * Creates new form SecretaryMainForm
     */
    public SecretaryMainForm() {
        initComponents();
    }
    
    public SecretaryMainForm(Secretary thisSecretary) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.userSecretary = thisSecretary;
        
        idLabel.setText(thisSecretary.getId());
        nameLabel.setText(thisSecretary.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CreationRequestsButton = new javax.swing.JButton();
        createAppointmentButton = new javax.swing.JButton();
        manageMedicinesButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        TerminationRequestsButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Secretary");

        CreationRequestsButton.setText("Pending Patient Creation Requests");
        CreationRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreationRequestsButtonActionPerformed(evt);
            }
        });

        createAppointmentButton.setText("Create an Appointment");
        createAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAppointmentButtonActionPerformed(evt);
            }
        });

        manageMedicinesButton.setText("Manage Medicines");
        manageMedicinesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedicinesButtonActionPerformed(evt);
            }
        });

        idLabel.setText("S0000");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        TerminationRequestsButton.setText("Pending Patient Termination Requests");
        TerminationRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminationRequestsButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreationRequestsButton)
                            .addComponent(idLabel)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOutButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createAppointmentButton)
                                .addGap(18, 18, 18)
                                .addComponent(manageMedicinesButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TerminationRequestsButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOutButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreationRequestsButton)
                    .addComponent(createAppointmentButton)
                    .addComponent(manageMedicinesButton))
                .addGap(18, 18, 18)
                .addComponent(TerminationRequestsButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm LoginInfo = new LoginForm();
        LoginInfo.setVisible(true);

        this.setDefaultCloseOperation(RequestPatientAccountForm.DISPOSE_ON_CLOSE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void CreationRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreationRequestsButtonActionPerformed
        // TODO add your handling code here:
        PendingPatientCreationRequestsForm creationInfo = new PendingPatientCreationRequestsForm(this.userSecretary);
        creationInfo.setVisible(true);
    }//GEN-LAST:event_CreationRequestsButtonActionPerformed

    private void TerminationRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminationRequestsButtonActionPerformed
        // TODO add your handling code here:
        PendingPatientTerminationRequestsForm terminationInfo = new PendingPatientTerminationRequestsForm(this.userSecretary);
        terminationInfo.setVisible(true);
    }//GEN-LAST:event_TerminationRequestsButtonActionPerformed

    private void createAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAppointmentButtonActionPerformed
        // TODO add your handling code here:
        CreateAppointmentForm createAppInfo = new CreateAppointmentForm(this.userSecretary);
        createAppInfo.setVisible(true);
    }//GEN-LAST:event_createAppointmentButtonActionPerformed

    private void manageMedicinesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedicinesButtonActionPerformed
        // TODO add your handling code here:
        ManageMedicinesForm manageMInfo = new ManageMedicinesForm(this.userSecretary);
        manageMInfo.setVisible(true);
    }//GEN-LAST:event_manageMedicinesButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreationRequestsButton;
    private javax.swing.JButton TerminationRequestsButton;
    private javax.swing.JButton createAppointmentButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton manageMedicinesButton;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
